version: '3.8'

services:
  app:
    build: 
      context: .
    depends_on:
      - mysql
      - redis
    command: sh -c "npx knex migrate:latest && npm install && npm run dev"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: expressjwtauth
      # REDIS_HOST: redis
      # REDIS_PORT: 6379
      # REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_URL: redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@redis:6379
  mysql:
    image: mysql:latest
    volumes:
      - expressjwtauth-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expressjwtauth
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - expressjwtauth-redis-data:/data

volumes:
  expressjwtauth-mysql-data:
  expressjwtauth-redis-data: