version: '3.8'

services:
  app:
    image: node:alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: expressjwtauth
  mysql:
    image: mysql:latest
    volumes:
      - expressjwtauth-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: expressjwtauth

volumes:
  expressjwtauth-mysql-data: